### ISSUE TITLE
export 'PortalModule' was not found in '@angular/cdk'

### ISSUE THREAD

**Issue by viggoChen** [NG-ZORRO/ng-zorro-antd#196]
<pre><code>
WARNING in ./node_modules/_ng-zorro-antd@0.5.0-rc.3@ng-zorro-antd/src/release/tabs/nz-tabs.module.js
21:40-52 "export 'PortalModule' was not found in '@angular/cdk'
    at HarmonyImportSpecifierDependency._getErrors (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\dependencies\Ha
rmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\dependencies\H
armonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\Compilation.j
s:677:24)
    at Compilation.finish (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:512:17)
    at D:\work\yxmgr-ng2\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (D:\work\yxmgr-ng2\node_modules\_webpack@3.4.1@webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
</code></pre>

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ng-zorro-antd version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by vthinkxie** [comment]
duplicated #191
