### ISSUE TITLE
Can't run tests on windows

### ISSUE THREAD

**Issue by saeedrahimi** [NG-ZORRO/ng-zorro-antd#4709]
### Reproduction link
[https://stackblitz.com/sorry-there-is-no-link](https://stackblitz.com/sorry-there-is-no-link)

### Steps to reproduce
1. Clone
2. npm install
3. npm test

### What is expected?
Expected to run tests

### What is actually happening?
```
> ng-zorro-antd@0.0.0-NOT-USED test C:\Users\******\Repos\ng-zorro-antd
> ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage

21 01 2020 08:25:14.558:INFO [karma-server]: Karma v4.3.0 server started at http://0.0.0.0:9877/
21 01 2020 08:25:14.569:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
21 01 2020 08:25:14.684:INFO [launcher]: Starting browser ChromeHeadless
21 01 2020 08:26:14.686:WARN [launcher]: ChromeHeadless have not captured in 60000 ms, killing.
21 01 2020 08:26:16.688:WARN [launcher]: ChromeHeadless was not killed in 2000 ms, sending SIGKILL.
21 01 2020 08:26:18.690:WARN [launcher]: ChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.

npm ERR! Test failed.  See above for more details.
```
| Environment | Info |
|---|---|
| ng-zorro-antd | 8.5.2 |
| Browser | - |

---
Environment:
Windows 10
node v10.15.0
npm 6.13.1

I've deleted `node-modules` and reinstalled it and tests failed again.
I googled and couldn't find any solution.

**Comment by vthinkxie** [comment]
cc @wendellhu95 
any solutions?

**Comment by wendellhu95** [comment]
Error reported on my PC:

```log
Handlebars: Access has been denied to resolve the property "branches" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See http://localhost:8080/api-reference/runtime-options.html#options-to-control-prototype-access for details
```

My env

```log
❯ node -v
v13.6.0
❯ npm -v
6.13.4
```

I will look into this.

**Comment by wendellhu95** [comment]
More on Windows:

`npm run test:watch` fails. Showing:

```log
❯ npm run test:watch rate

> ng-zorro-antd@0.0.0-NOT-USED test:watch C:\Users\wendellhu\Developer\OSS\ng-zorro-antd
> gulp test:watch --tags $tags "rate"

[18:21:12] Using gulpfile ~\Developer\OSS\ng-zorro-antd\gulpfile.js
[18:21:12] Task never defined: rate
[18:21:12] To list available tasks, try running: gulp --tasks
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-zorro-antd@0.0.0-NOT-USED test:watch: `gulp test:watch --tags $tags "rate"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-zorro-antd@0.0.0-NOT-USED test:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wendellhu\AppData\Roaming\npm-cache\_logs\2020-01-22T10_21_13_005Z-debug.log
```

**Comment by wendellhu95** [comment]
`npm run start` fails to watch demo files' change.

**Comment by wendellhu95** [comment]
@saeedrahimi Try to reinstall dependency and run tests. It seems that there is a breaking change in the underlying dependencies.

**Comment by saeedrahimi** [comment]
reinstalled dependency and still fails.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@6.13.1
3 info using node@v10.15.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle ng-zorro-antd@0.0.0-NOT-USED~pretest: ng-zorro-antd@0.0.0-NOT-USED
6 info lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: ng-zorro-antd@0.0.0-NOT-USED
7 verbose lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: unsafe-perm in lifecycle true
8 verbose lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: PATH: XXX Trimmed XXX
9 verbose lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: CWD: C:\Users\xxxx\Source\Repos\ng-zorro-antd
10 silly lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: Args: [ '/d /s /c',
10 silly lifecycle   'ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage' ]
11 silly lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: Returned: code: 1  signal: null
12 info lifecycle ng-zorro-antd@0.0.0-NOT-USED~test: Failed to exec test script
13 verbose stack Error: ng-zorro-antd@0.0.0-NOT-USED test: `ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ng-zorro-antd@0.0.0-NOT-USED
15 verbose cwd C:\Users\xxxxx\Source\Repos\ng-zorro-antd
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v10.15.0
19 verbose npm  v6.13.1
20 error code ELIFECYCLE
21 error errno 1
22 error ng-zorro-antd@0.0.0-NOT-USED test: `ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage`
22 error Exit status 1
23 error Failed at the ng-zorro-antd@0.0.0-NOT-USED test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by wendellhu95** [comment]
It seems that ChromeHeadlessCI failed to bootup. You can try to remove the parameter in the npm script:

```diff
- "test": "ng test --no-watch --no-progress --browser=ChromeHeadlessCI --code-coverage",
+ "test": "ng test --no-watch --no-progress --code-coverage",
```

**Comment by Mr-Eve** [comment]
In the zorro v9, in my win10, I can run `npm run test` successful. But `npm run test:watch rate` failed. 
![image](https://user-images.githubusercontent.com/30228406/80272440-ebd8f900-86fb-11ea-8f98-159107fe6efe.png)

**Comment by wendellhu95** [comment]
> In the zorro v9, in my win10, I can run `npm run test` successful. But `npm run test:watch rate` failed.
> ![image](https://user-images.githubusercontent.com/30228406/80272440-ebd8f900-86fb-11ea-8f98-159107fe6efe.png)

PR is welcome. 😋

**Comment by Mr-Eve** [comment]
About what? For component issues, maybe I can help. For gulp or something else about enviroment stuff, I can't, I'm not familiar with it :p
