### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by SunnyXiao** [NG-ZORRO/ng-zorro-antd#6040]
### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
1. update ng-zorror-antd@9.0 to ng-zorror-antd@10.0 or ng-zorror-antd@10.1.1
2. run `npm run build`

### What is expected?
build seccussfully

### What is actually happening?
there is an error as bellow:
![微信截图_20201110165621](https://user-images.githubusercontent.com/18277688/98651822-b2a16700-2375-11eb-8b3a-2080cec13f07.png)

[error] JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: auto   1
^..^
    at D:\workspace\Projects\savillis-web\styles.6610579ed6c222d53406.css:21785:3
    at Object.parseError (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:2333:44)
    at Object.lexer_next [as next] (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:3403:18)
    at fastLex (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:1603:27)
    at Parser.parse (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\parser.js:1677:30)
    at D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\lib\transform.js:33:30
    at walk (D:\workspace\Projects\savillis-web\node_modules\postcss-value-parser\lib\walk.js:7:16)
    at ValueParser.walk (D:\workspace\Projects\savillis-web\node_modules\postcss-value-parser\lib\index.js:18:3)
    at transformValue (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\lib\transform.js:24:50)
    at _default (D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\lib\transform.js:66:100)
    at D:\workspace\Projects\savillis-web\node_modules\postcss-calc\dist\index.js:27:32
    at D:\workspace\Projects\savillis-web\node_modules\postcss\lib\container.js:135:18
    at Rule.each (D:\workspace\Projects\savillis-web\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (D:\workspace\Projects\savillis-web\node_modules\postcss\lib\container.js:131:17)
    at D:\workspace\Projects\savillis-web\node_modules\postcss\lib\container.js:148:24

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.0.0 |
| Browser | - |

**Comment by vthinkxie** [comment]
plz check your style files
it is an error caused by the postcss, plz track
https://github.com/postcss/postcss-calc/issues/89

**Comment by Kangcor** [comment]
Sorry to reopen the issue, but I had the same error, the cause was in theme.less file, line 315:
`
@zindex-table-fixed: auto;
`

This cause the css code to be:
`
z-index: calc(auto + 1);
`
Which is incorrect css.

Without that line, the build is done without further issues.

**Comment by vthinkxie** [comment]
Hi @Kangcor 
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less#L333

**Comment by Kangcor** [comment]
> Hi @Kangcor
> https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/style/themes/default.less#L333

Yeah, you are absolutely right, I had an outdated version of the default theme, thanks for the input.
