### ISSUE TITLE
ng build --prod error

### ISSUE THREAD

**Issue by alexspring123** [NG-ZORRO/ng-zorro-antd#614]
## Version

0.6.1

## Environment

macos ng-zorro 0.6.1

## Reproduction link

[https://github.com/NG-ZORRO/ng-zorro-antd](https://github.com/NG-ZORRO/ng-zorro-antd)

## Steps to reproduce

1. ng set --global packageManager=cnpm
2. ng new NG-ZORRO
3. cd NG-ZORRO
4. cnpm install ng-zorro-antd --save
5. ng build --prod

got error when execute ng build --prod
```
localhost:NG-ZORRO alex$ ng build --prod
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open '/Users/alex/Downloads/NG-ZORRO/node_modules/_@angular_core@5.0.3@@angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at LicenseExtractor.readPackageJson (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/ModuleProcessor.js:21:21)
    at moduleCallback (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:80:61)
    at SortableSet.forEach (native)
    at Chunk.forEachModule (/Users/alex/Downloads/NG-ZORRO/node_modules/_webpack@3.8.1@webpack/lib/Chunk.js:159:17)
    at /Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:89:27
    at Array.forEach (native)
    at Compiler.<anonymous> (/Users/alex/Downloads/NG-ZORRO/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:65:32)
    at next (/Users/alex/Downloads/NG-ZORRO/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /Users/alex/Downloads/NG-ZORRO/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/Users/alex/Downloads/NG-ZORRO/node_modules/_bluebird@3.5.1@bluebird/js/release/finally.js:56:23)
```

## What is expected?

no error

## What is actually happening?

got error

**Comment by vthinkxie** [comment]
try `cnpm install ng-zorro-antd --save --by=npm`

**Comment by alexspring123** [comment]
@vthinkxie  
1. ng set --global packageManager=cnpm
2. ng new NG-ZORRO
3. cd NG-ZORRO
4. cnpm install ng-zorro-antd --save --by=npm
got error:
```
localhost:NG-ZORRO alex$ cnpm install ng-zorro-antd --save --by=npm
npm WARN gentlyRm not removing /Users/alex/Downloads/NG-ZORRO/node_modules/.bin/webdriver-manager as it wasn't installed by /Users/alex/Downloads/NG-ZORRO/node_modules/_webdriver-manager@12.0.6@webdriver-manager
npm WARN webpack-dev-middleware@1.12.1 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/alex/Downloads/NG-ZORRO/node_modules/@angular-devkit/build-optimizer/node_modules/loader-utils
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/alex/Downloads/NG-ZORRO/node_modules/@angular-devkit/build-optimizer/node_modules/loader-utils' -> '/Users/alex/Downloads/NG-ZORRO/node_modules/@angular-devkit/build-optimizer/node_modules/loader-utils'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2017-11-27T02_58_37_903Z-debug.log
```

**Comment by vthinkxie** [comment]
try remove all node_modules and reinstall with --by=npm

**Comment by alexspring123** [comment]
thinks!
```
ng set --global packageManager=npm
rm -rf node_modules/ dist
npm install --by=npm
```
It fix my problem.

but, I don't known why.
