### ISSUE TITLE
nzType的值不是danger也会打印警告信息

### ISSUE THREAD

**Issue by itning** [NG-ZORRO/ng-zorro-antd#6187]
### Reproduction link
[https://stackblitz.com/edit/angular-hm2opi?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-hm2opi?file=src/app/app.component.ts)

### Steps to reproduce
1.打开Console可以看到警告信息

### What is expected?
控制台无警告

### What is actually happening?
控制台出现警告信息:
```
ng-zorro-antd-core-logger.js:30 [NG-ZORRO]: deprecated: 'danger' value of 'nzType' in Button is going to be removed in 12.0.0. Please use 'nzDanger' instead. Error
    at warnDeprecation (http://localhost:4200/vendor.js:13016:23)
    at NzButtonComponent.ngOnChanges (http://localhost:4200/vendor.js:25766:94)
    at NzButtonComponent.rememberChangeHistoryAndInvokeOnChangesHook (http://localhost:4200/vendor.js:54542:14)
    at callHook (http://localhost:4200/vendor.js:55454:14)
    at callHooks (http://localhost:4200/vendor.js:55420:17)
    at executeInitAndCheckHooks (http://localhost:4200/vendor.js:55372:9)
    at refreshView (http://localhost:4200/vendor.js:59510:21)
    at refreshEmbeddedViews (http://localhost:4200/vendor.js:60596:17)
    at refreshView (http://localhost:4200/vendor.js:59519:9)
    at refreshEmbeddedViews (http://localhost:4200/vendor.js:60596:17)
```

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.2.1 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 |

**Comment by itning** [comment]
Debug in console:

![image](https://raw.githubusercontent.com/itning/FilePool/master/images/2020-12-13-222015.jpg)
