### ISSUE TITLE
Error Router Tab

### ISSUE THREAD

**Issue by oluevanocadena** [NG-ZORRO/ng-zorro-antd#7501]
### Reproduction link
[https://www.stackblitz.com/](https://www.stackblitz.com/)

### Steps to reproduce
Make tabs and show when this error appears

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at equalPath (router.mjs:878:12)
    at equalSegmentGroups (router.mjs:676:10)
    at equalSegmentGroups (router.mjs:686:14)
    at Object.equalSegmentGroups [as exact] (router.mjs:686:14)
    at containsTree (router.mjs:667:12)
    at Router.isActive (router.mjs:5022:20)
    at ng-zorro-antd-tabs.mjs:1580:22
    at ng-zorro-antd-tabs.mjs:1575:50
    at Array.findIndex (<anonymous>)
    at NzTabSetComponent.findShouldActiveTabIndex (ng-zorro-antd-tabs.mjs:1573:21)

### What is expected?
Dont break at this tabs method

### What is actually happening?
When pages loads appears this error on tabs component

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.2.2 |
| Browser | Chrome 102.5 |

---
package.json

"dependencies": {
    "@angular/animations": "~14.0.0",
    "@angular/common": "~14.0.0",
    "@angular/compiler": "~14.0.0",
    "@angular/core": "~14.0.0",
    "@angular/forms": "~14.0.0",
    "@angular/platform-browser": "~14.0.0",
    "@angular/platform-browser-dynamic": "~14.0.0",
    "@angular/router": "~14.0.0",
    "file-saver": "^2.0.5",
    "moment": "^2.29.3",
    "momentjs": "^2.0.0",
    "ng-block-ui": "^3.0.2",
    "ng-zorro-antd": "^13.2.2",
    "ngx-cookie-service": "^13.2.1",
    "ngx-useful-swiper": "^10.0.1",
    "numeral": "^2.0.6",
    "rxjs": "~7.5.0",
    "swiper": "^8.0.6",
    "tslib": "^2.4.0",
    "underscore": "^1.13.3",
    "xlsx": "^0.18.5",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.0.0",
    "@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "~14.0.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.2"
  }

**Comment by volvachev** [comment]
Hi, could you please update the `stackblitz` link for your example.
