### ISSUE TITLE
nzpopover on nz-input field

### ISSUE THREAD

**Issue by egalley** [NG-ZORRO/ng-zorro-antd#7517]
### Reproduction link
[https://stackblitz.com/edit/angular-za6bv7?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-za6bv7?file=src/app/app.component.ts)

### Steps to reproduce
 <input nz-input ... nz-popover nzPopoverContent="Hey"> in a form-control

### What is expected?
"Hey" should be displayed as it was working in previous releases

### What is actually happening?
Nothing display.
ERROR TypeError: Cannot read properties of undefined (reading 'overlayRef')
    at ng-zorro-antd-tooltip.mjs:147:92
    at HTMLInputElement.<anonymous> (platform-browser.mjs:466:38)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1661:1)
    at globalCallback (zone.js:1692:1)
    at HTMLInputElement.globalZoneAwareCallback (zone.js:1725:1)

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.0 |
| Browser | Chrome 102.0.5005.115  |

**Comment by simplejason** [comment]
Move `nz-popover` to `nz-input-group` instead of `input`
