### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'nzHide')     at ng-zorro-antd-select.mjs:1273:35

### ISSUE THREAD

**Issue by skwny** [NG-ZORRO/ng-zorro-antd#7914]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Unable to reproduce in sandbox environments. I'm hoping someone can point me in right direction to help debug.

### What is expected?
Not errors

### What is actually happening?
This is the console error I'm seeing:

```
load-member-data.component.html:255 ERROR TypeError: Cannot read properties of undefined (reading 'nzHide')
    at ng-zorro-antd-select.mjs:1273:35
```

Line 255 is the below code:
```
  <button
    nz-button nzBlock nzSize=large nzType=primary

    // Line 255 is the next line.
    [disabled]='is_saving || !is_valid' [nzLoading]=is_saving

    (click)=submit()>
    Submit
  </button>
```
I'm seeing errors in the console when component with nz-select loads. The stack trace starts here:

```
updateListOfContainerItem() {
        let listOfContainerItem = this.listOfTagAndTemplateItem
            // Next line is the line the stack trace points to.
            .filter(item => !item.nzHide)
            .filter(item => {
```

This is also showing for many `nz-select` elements.

| Environment | Info |
|---|---|
| ng-zorro-antd | 14.3.0 |
| Browser | 112.0.5615.49 |

**Comment by skwny** [comment]
Turns out I was passing empty objects to nz-options. Closing!
