### ISSUE TITLE
Angular 17 - Missing "./core/transition-patch/transition-patch.module" specifier in "ng-zorro-antd" package

### ISSUE THREAD

**Issue by Tjax33** [NG-ZORRO/ng-zorro-antd#8311]
### Reproduction link
[https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Just install the latest package 17.0.1 in package.json and run your app

### What is expected?
To not have any errors

### What is actually happening?
This error message appears on npm run start
An unhandled exception occurred: Missing "./core/transition-patch/transition-patch.module" specifier in "ng-zorro-antd" package

The detailed log states this
[error] Error: Missing "./core/transition-patch/transition-patch.module" specifier in "ng-zorro-antd" package
    at e (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:25)
    at n (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:627)
    at o (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:1297)
    at resolveExportsOrImports (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28746:20)
    at resolveDeepImport (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28765:31)
    at tryNodeResolve (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)
    at Context.resolveId (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28212:28)
    at Object.resolveId (file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44276:64)
    at async file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65929:21
    at async file:///C:/Users/david/RiderProjects/cornerstone_clientportal_ui/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44925:20

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.0.1 |
| Browser | Chrome |

**Comment by Brown000** [comment]
@Tjax33 Hi, I have a much similar error, which says "Missing "./core/transition-patch/transition-patch.directive" specifier in "ng-zorro-antd" package". Just a minute before, I was developing as normal and after I changed some code and "ctrl+s", the error throwed. Seeing you closed this issue, I am glad to hear the solution.

**Comment by ParsaArvanehPA** [comment]
> @Tjax33 Hi, I have a much similar error, which says "Missing "./core/transition-patch/transition-patch.directive" specifier in "ng-zorro-antd" package". Just a minute before, I was developing as normal and after I changed some code and "ctrl+s", the error throwed. Seeing you closed this issue, I am glad to hear the solution.

@Brown000 
Hi, check the import section of your component, see if there is a `transitionPatch` there; if so just remove it and you should be fine.

**Comment by Brown000** [comment]
@ParsaArvanehPA Hi, that worked for me! Thanks a lot.
