### ISSUE TITLE
Error reported using universal startup in ng-zorro 15.1.0

### ISSUE THREAD

**Issue by CacoCode** [NG-ZORRO/ng-zorro-antd#8312]
### Steps to reproduce
- ng add @nguniversal/express-engine@15.2.0
- npm run dev:ssr

### What is expected?
Normal start-up

### What is actually happening?
✔ Index html generation complete.
⠙ Generating service worker...
Compiled successfully.
✔ Service worker generation complete.
⠋ Generating index html...
19 unchanged chunks

Build at: 2023-12-20T13:05:34.195Z - Hash: ec4850a75b79e77f - Time: 4716ms
✔ Index html generation complete.
⠙ Generating service worker...
Compiled successfully.
✔ Service worker generation complete.

19 unchanged chunks

Build at: 2023-12-20T13:05:35.209Z - Hash: ec4850a75b79e77f - Time: 4247ms

Compiled successfully.
./node_modules/ng-zorro-antd/fesm2020/ng-zorro-antd-graph.mjs:849
Selection.bind('transition', transition);
^

ReferenceError: Selection is not defined
    at Module.67391 (./node_modules/ng-zorro-antd/fesm2020/ng-zorro-antd-graph.mjs:849:1)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.8963 (./src/app/app.server.module.ts:10:17)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.63370 (./src/app/app.component.html:265:20)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.84362 (./src/app/app.module.ts:56:24)
    at __webpack_require__ (./webpack/bootstrap:19:1)
    at Module.23149 (./src/environments/environment.ts:18:1)
    at __webpack_require__ (./webpack/bootstrap:19:1)

Node.js v18.15.0

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED ::1:57792

| Environment | Info |
|---|---|
| ng-zorro-antd | 15.1.0 |
| Browser | Chrome |

**Comment by CacoCode** [comment]
NzGraphModule module problem, just remove NzGraphModule
NzGraphModule 模块的问题，去掉NzGraphModule就好了
