### ISSUE TITLE
Docs issue: sometimes changing components not work

### ISSUE THREAD

**Issue by Laffery** [NG-ZORRO/ng-zorro-antd#8510]
### Reproduction link

https://ng.ant.design/experimental/pipes/zh

### Steps to reproduce

way 1:
1. enter the doc site
2. change components, repeat as more as possible

way2:
1. visit https://ng.ant.design/experimental/pipes/zh
2. reload the window

### What is expected?
Nothing wrong

### What is actually happening?
1. error in console
```txt
chunk-NOKK6CHT.js:7 ERROR TypeError: t.hasAttribute is not a function
    at u7 (chunk-NOKK6CHT.js:7:28447)
    at FC (chunk-NOKK6CHT.js:7:48131)
    at RC (chunk-NOKK6CHT.js:7:48094)
    at NC (chunk-NOKK6CHT.js:7:48071)
    at Mo.create (chunk-NOKK6CHT.js:7:70206)
    at bf.createComponent (chunk-NOKK6CHT.js:7:73895)
    at new e (chunk-NOKK6CHT.js:13:247232)
    at e.ɵfac [as factory] (chunk-NOKK6CHT.js:13:247459)
    at fr (chunk-NOKK6CHT.js:7:23904)
    at WC (chunk-NOKK6CHT.js:7:51361)
```

3. failed to navigate to new component page and something wrong in the page:

![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/49607541/d4903c49-f130-41e8-a747-5e0a96419dbf)

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.4.0 |
| Browser | Chrome latest |

**Comment by Laffery** [comment]
https://github.com/angular/angular/issues/50133
